---
title: "Potions Task Plots"
author: "Cody Moser"
date: '2023-01-09'
output: html_document
---

Load data and package:
```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(tidyverse)
library(patchwork)
library(viridis)

path<-('.../git/Potions-Model/Results/')

#Import data, calculate Combination Time, and scale Gini variables
random <- read.csv(paste(path,"random.csv", sep='')) %>% 
  filter(Crossover == 1) %>% 
  mutate(ProbDiff = 1 - ProbDiff,
         ChangeLink = 1 - ChangeLink,
         CombTime = NumAgents*Step,
         Gini = scale(Gini))

caveman <-read.csv(paste(path,'caveman.csv',sep='')) %>% 
  filter(Crossover == 1) %>% 
  mutate(ProbDiff = 1 - ProbDiff,
         ChangeLink = 1 - ChangeLink,
         CombTime = NumAgents*Step,
         Gini = scale(Gini))

ring <-read.csv(paste(path,'ring.csv',sep='')) %>% 
  filter(Crossover == 1) %>% 
  mutate(ProbDiff = 1 - ProbDiff,
         ChangeLink = 1 - ChangeLink,
         CombTime = NumAgents*Step,
         Gini = scale(Gini))

RW <-read.csv(paste(path,'realworld.csv',sep='')) %>% 
  filter(Crossover == 1) %>% 
  mutate(CombTime = NumAgents*Step,
         Gini = scale(Gini))

infernoyellow <- c("#fde725", "#FCA50AFF", "#DD513AFF", "#932667FF", "#420A68FF", "#000004FF")
```


Population Size and Connectivity Plots:
```{r}
pop<- ggplot(data=random %>% 
                    mutate(NumAgents = as.factor(NumAgents)) %>%
                    filter(ChangeLink == 0,
                           NumAgents != 5,
                           ProbDiff == 1)
                  ,aes(y=Step, x=ProbEdge,color=NumAgents))+
  stat_summary(fun="mean", geom="point", show.legend=F)+
  stat_summary(fun="mean", geom="line", show.legend=F,size=1.3,size=1.3)+
  theme_bw()+
  theme(plot.title=element_text(hjust=0.5,size=20,margin=margin(b=10)),
        axis.title.y = element_text(margin=margin(r=20),size=20),
        text=element_text(size=12),
        aspect.ratio=.8)+
  scale_color_viridis(discrete=T)+
  labs(title="Network Connectivity",
       x="",
       y="Steps to Crossover",
       color="Number\nof Agents")

popcomb<- ggplot(data=random %>% 
                    mutate(NumAgents = as.factor(NumAgents)) %>%
                    filter(ChangeLink == 0,
                           NumAgents != 5,
                           ProbDiff == 1)
                  ,aes(y=CombTime, x=ProbEdge,color=NumAgents))+
  stat_summary(fun="mean", geom="point", show.legend=F)+
  stat_summary(fun="mean", geom="line", show.legend=F,size=1.3,size=1.3)+
  theme_bw()+
  theme(plot.title=element_text(hjust=0.5,size=20,margin=margin(b=10)),
        axis.title.y = element_text(margin=margin(r=15),size=20),
        text=element_text(size=12),
        aspect.ratio=.8)+
  scale_color_viridis(discrete=T,option="mako")+
  labs(x="",
       y="Combinations to Crossover",
       color="Number\nof Agents")

popgini<- ggplot(data=random %>% 
                    mutate(NumAgents = as.factor(NumAgents)) %>%
                    filter(ChangeLink == 0,
                           NumAgents != 5,
                           ProbDiff == 1)
                  ,aes(y=Gini, x=ProbEdge,color=NumAgents))+
  stat_summary(fun="mean", geom="point", show.legend=F)+
  stat_summary(fun="mean", geom="line", show.legend=F,size=1.3)+
  theme_bw()+
  theme(plot.title=element_text(hjust=0.5, size=20,margin=margin(b=10)),
        axis.title.y = element_text(margin=margin(r=20),size=20),
        text=element_text(size=12),
        aspect.ratio=.8,
        legend.title.align = 0.5,
        axis.title.x = element_text(size=15))+
    scale_color_manual(values=infernoyellow)+
  labs(
       y="Gini Coefficient",
       x="Edge Probability",
       color="Number\nof Agents")+
    guides(colour = guide_legend(override.aes = list(size=3)))

pop+popcomb+popgini
```

Diffusion Plots:
```{r}
diff<-ggplot(data=random %>% 
                    filter(NumAgents > 5) %>%
                    mutate(NumAgents = as.factor(NumAgents)) %>%
                    filter(ChangeLink == 0) %>%
                    filter(ProbEdge == 1)
                  ,aes(y=Step, x=ProbDiff,color=NumAgents))+
  stat_summary(fun="mean", geom="point", show.legend=F)+
  stat_summary(fun="mean", geom="line", show.legend=F,size=1.3)+
  theme_bw()+
  theme(plot.title=element_text(hjust=0.5,size=20,margin=margin(b=10)),
        text=element_text(size=12),
                axis.title.y = element_text(margin=margin(r=20)),
        aspect.ratio=.8)+
    scale_color_viridis(discrete=T)+
  labs(y="",
       title="Information Diffusion",
       x="",
       color="Number\nof Agents")

diffcomb<-ggplot(data=random %>% 
                    filter(NumAgents > 5) %>%
                    mutate(NumAgents = as.factor(NumAgents)) %>%
                    filter(ChangeLink == 0) %>%
                    filter(ProbEdge == 1)
                  ,aes(y=CombTime, x=ProbDiff,color=NumAgents))+
  stat_summary(fun="mean", geom="point", show.legend=F)+
  stat_summary(fun="mean", geom="line", show.legend=F,size=1.3)+
  theme_bw()+
  theme(plot.title=element_text(hjust=0.5,size=20,margin=margin(b=10)),
        text=element_text(size=12),
                axis.title.y = element_text(margin=margin(r=20)),
        aspect.ratio=.8)+
    scale_color_viridis(discrete=T,option="mako")+
  labs(y="",
       x="",
       color="Number\nof Agents")

diffgini<-ggplot(data=random %>% 
                    filter(NumAgents > 5) %>%
                    mutate(NumAgents = as.factor(NumAgents)) %>%
                    filter(ChangeLink == 0) %>%
                   filter(ProbEdge == 1)
                  ,aes(y=Gini, x=ProbDiff,color=NumAgents))+
  stat_summary(fun="mean", geom="point", show.legend=F)+
  stat_summary(fun="mean", geom="line", show.legend=F,size=1.3)+
  theme_bw()+
  theme(plot.title=element_text(hjust=0.5),
        text=element_text(size=12),
        aspect.ratio=.8,
                axis.title.x = element_text(size=15))+
  scale_color_manual(values=infernoyellow)+
  labs(x="Diffusion Probability",
       y="",
       color="")+
    scale_y_continuous(labels = function(x) format(x, nsmall = 2))+
    guides(colour = guide_legend(override.aes = list(size=3)))

diff+diffcomb+diffgini
```

Dynamic Network Plots:
```{r}
change<-ggplot(data=random %>% 
                     filter(NumAgents > 5) %>%
                     mutate(NumAgents = as.factor(NumAgents)) %>%
                     mutate(ProbEdge = as.factor(ProbEdge)) %>%
                     filter(ProbDiff == 1)
                   ,aes(y=Step, x=ChangeLink,color=NumAgents))+
  stat_summary(fun="mean", geom="point", show.legend=T)+
  stat_summary(fun="mean", geom="line", show.legend=F,size=1.3)+
  theme_bw()+
  theme(plot.title=element_text(hjust=0.5,size=20,margin=margin(b=10)),
        text=element_text(size=12),
        axis.title.y = element_text(margin=margin(r=20)),
        aspect.ratio=.8,
        legend.title.align = 0.5,
        legend.title=element_text(size=14))+
    scale_color_viridis(discrete=T)+
  labs(title="Dynamic Networks",
       y="",
      color="Population\nSize",
      x="")+
    guides(colour = guide_legend(override.aes = list(size=5)))

changecomb<-ggplot(data=random %>% 
                     filter(NumAgents > 5) %>%
                     mutate(NumAgents = as.factor(NumAgents)) %>%
                     mutate(ProbEdge = as.factor(ProbEdge)) %>%
                     filter(ProbDiff == 1)
                   ,aes(y=CombTime, x=ChangeLink,color=NumAgents))+
  stat_summary(fun="mean", geom="point", show.legend=T)+
  stat_summary(fun="mean", geom="line", show.legend=F,size=1.3)+
  theme_bw()+
  theme(plot.title=element_text(hjust=0.5,size=20,margin=margin(b=10)),
        text=element_text(size=12),
        axis.title.y = element_text(margin=margin(r=20)),
        aspect.ratio=.8,
        legend.title.align = 0.5)+
    scale_color_viridis(discrete=T,option="mako")+
  labs(y="",
      color="",
      x="")+
    guides(colour = guide_legend(override.aes = list(size=5)))

changegini<-ggplot(data=random %>%
                     filter(NumAgents > 5) %>%
                     mutate(NumAgents = as.factor(NumAgents)) %>%
                     mutate(ProbEdge = as.factor(ProbEdge)) %>%
                     filter(ProbDiff == 1)
                   ,aes(y=Gini, x=ChangeLink,color=NumAgents))+
  stat_summary(fun="mean", geom="point", show.legend=T)+
  stat_summary(fun="mean", geom="line", show.legend=F,size=1.3)+
  theme_bw()+
  theme(plot.title=element_text(hjust=0.5),
        text=element_text(size=12),
                axis.title.y = element_text(margin=margin(r=19)),
        aspect.ratio=.8,
        axis.title.x = element_text(size=15),
                legend.title.align = 0.5)+
  scale_color_manual(values=infernoyellow)+
  labs(color="",
       x="Link Alteration Probability",
       y="")+
  scale_y_continuous(labels = function(x) format(x, nsmall = 2))+
  guides(colour = guide_legend(override.aes = list(size=5)))

change+changecomb+changegini
```

Combine all plots (Figure 2):
```{r}
top_row<-plot_grid(pop,popgini)
mid_row<-plot_grid(diff,diffgini)
bottom_row<-plot_grid(change,changegini)
plot_grid(top_row,mid_row,bottom_row,
          ncol=1,
          labels=c("A","B","C"))

#Layout specified using patchwork library
layout2<-"
ADG
BEH
CFI"

Fig2<-pop+popcom+popgini+diff+diffcomb+diffgini+change+changecomb+changegini+
  plot_layout(design=layout2)+
  plot_annotation(tag_levels = 'A')

Fig2
```

Scatterplot (Fig. 3)
```{r}
#Alter the original datasets so that they are just the normalized Gini, normalized step, normalized CombTime, and each parameter combination

randscatter<-random %>%
  unite("Param", 2:5) %>%
  select(Gini,Step,CombTime,Param) %>%
  mutate(Step=scale(Step),
         CombTime=scale(CombTime)) %>%
  group_by(Param) %>%
  summarise_if(is.numeric,mean,na.rm=T) %>%
  mutate(Network="Random")
  
ringscatter<-ring %>%
  unite("Param", 2:4) %>%
  select(Gini,Step,CombTime,Param) %>%
  mutate(Step=scale(Step),
         CombTime=scale(CombTime)) %>%
  group_by(Param) %>%
  summarise_if(is.numeric,mean,na.rm=T) %>%
  mutate(Network="Ring")

cavescatter<-caveman %>%
  unite("Param", 2:5) %>%
  select(Gini,Step,CombTime,Param) %>%
  mutate(Step=scale(Step),
         CombTime=scale(CombTime)) %>%
  group_by(Param) %>%
  summarise_if(is.numeric,mean,na.rm=T) %>%
  mutate(Network="Caveman")

RWscatter<-RW %>%
    select(Gini,Step,CombTime,Network) %>%
    mutate(Step=scale(Step),
          CombTime=scale(CombTime)) %>%
  group_by(Network) %>%
  summarise_if(is.numeric,mean,na.rm=T) %>%
  mutate(Param=Network,
         Network="Real World")

scatter<- list(randscatter,ringscatter,cavescatter) %>%
  reduce(full_join) %>%
  mutate(Network = factor(Network, levels=c("Random","Caveman","Ring","Real World")))

#Create the Scatterplots
scatstep<-ggplot()+
  geom_point(data=scatter,aes(y=Step, x=Gini,color=Network),alpha=0.3,show.legend=T)+
  geom_point(data=RWscatter,aes(y=Step, x=Gini),color="black")+
  ggrepel::geom_text_repel(data=RWscatter,aes(y=Step, x=Gini,label=Param),show.legend = F)+
  theme_bw()+
  theme(plot.title=element_text(hjust=0.5,size=20,margin=margin(b=10)),
        text=element_text(size=15),
        axis.title.y = element_text(margin=margin(r=20)),
        legend.title= element_text(size=15),
        aspect.ratio=1,
        legend.title.align = 0.5)+
  labs(title="Inequality and Performance\nAcross All Networks",
       y="Steps (Scaled)",
       x="",
       color="Network")+
    guides(colour = guide_legend(override.aes = list(size=5,alpha=1)))+
    scale_color_viridis(discrete=T, direction = -1)


scatcomb<-ggplot()+
  geom_point(data=scatter,aes(y=CombTime, x=Gini,color=Network),alpha=0.3,show.legend=F)+
  geom_point(data=RWscatter,aes(y=CombTime, x=Gini),color="black")+
  ggrepel::geom_text_repel(data=RWscatter,aes(y=CombTime, x=Gini,label=Param),show.legend = F)+
  theme_bw()+
  theme(plot.title=element_text(hjust=0.5,size=20,margin=margin(b=10)),
        text=element_text(size=15),
        axis.title.y = element_text(margin=margin(r=20)),
        legend.title= element_text(size=15),
        aspect.ratio=1,
        legend.title.align = 0.5)+
  labs(y="Combinations (Scaled)",
      color="Network",
      x="Gini Coefficient (Scaled)")+
  guides(colour = guide_legend(override.aes = list(alpha=1)))+
  scale_color_viridis(discrete=T,direction=-1)

scatlayout<-"
A
B"

Fig3<-scatstep+scatcomb+
  plot_layout(design=scatlayout)+
  plot_annotation(theme = theme(plot.title = element_text(hjust = 0.5,size=25)),
                  tag_levels = "A")

Fig3
```

Caveman Plots (Figure 4):
```{r}
cavegraph<-ggplot(data=caveman %>%
                   mutate(CliqueSize = as.factor(CliqueSize)) %>%
                   filter(ChangeLink == 0,
                          NumAgents > 6,
                          CliqueSize != 8,
                          ProbDiff == 1),
                 aes(y=Step, x=NumAgents, color= CliqueSize))+
  stat_summary(fun="mean",geom="point",show.legend=T)+
  stat_summary(fun="mean", geom="line", show.legend=F,size=1)+
  theme_bw()+
  theme(plot.title=element_text(hjust=0.5,size=18,margin=margin(b=10)),
        text=element_text(size=15),
                aspect.ratio=.8,
        legend.title.align = 0.5,
                axis.title.y = element_text(margin=margin(r=20),size=15))+
  labs(title="Connected Caveman\nNetworks",
       x="",
       y="Steps to Crossover",
       color="Clique\nSize")+
    guides(colour = guide_legend(override.aes = list(size=5)))+
      scale_color_viridis(discrete=T)


cavegini<-ggplot(data=caveman %>%
                   mutate(CliqueSize = as.factor(CliqueSize)) %>%
                   filter(ChangeLink == 0,
                  CliqueSize != 8,
                  NumAgents > 6,
                          ProbDiff == 1),
                 aes(y=Gini, x=NumAgents, color= CliqueSize))+
  stat_summary(fun="mean",geom="point",show.legend=T)+
  stat_summary(fun="mean", geom="line", show.legend=F,size=1)+
  theme_bw()+
  theme(plot.title=element_text(hjust=0.5),
        text=element_text(size=15),
                aspect.ratio=.8,
                axis.title.x = element_text(size=15),
                axis.title.y = element_text(margin=margin(r=20),size=15))+
  labs(title="",
       x="Number of Agents",
       y="Gini Coefficient",
       color="")+
    guides(colour = guide_legend(override.aes = list(size=5)))+
    scale_color_manual(values=c('#000004','#781c6d', '#ed6925','#fde725'))

#Layout specified using patchwork library
cavelayout<-"
A
B"

Fig4<-cavegraph+cavegini+
  plot_layout(design=cavelayout)+
  plot_annotation(tag_levels = 'A')

Fig4
```


Caveman Connectivity Plot:
```{r}
cc1<-ggplot(data=caveman %>% 
                     filter(CliqueSize == 3) %>%
                     mutate(CliqueNum = as.factor(CliqueNum)) %>%
                     filter(ProbDiff == 1)
                   ,aes(y=Step, x=ChangeLink,color=CliqueNum))+
  stat_summary(fun="mean", geom="point", show.legend=T)+
  stat_summary(fun="mean", geom="line", show.legend=F,size=1.3)+
  theme_bw()+
  theme(plot.title=element_text(hjust=0.5,size=20,margin=margin(b=10)),
        text=element_text(size=12),
        axis.title.y = element_text(margin=margin(r=20)),
        aspect.ratio=1,
        legend.title.align = 0.5)+
    scale_color_viridis(discrete=T)+
  labs(title="",
       y="k=3",
      color=expression(n[k]),
      x="")+
    guides(colour = guide_legend(override.aes = list(size=2)))

cc2<-ggplot(data=caveman %>% 
                     filter(CliqueSize==4) %>%
                     mutate(CliqueNum = as.factor(CliqueNum)) %>%
                     filter(ProbDiff == 1)
                   ,aes(y=Step, x=ChangeLink,color=CliqueNum))+
  stat_summary(fun="mean", geom="point", show.legend=T)+
  stat_summary(fun="mean", geom="line", show.legend=F,size=1.3)+
  theme_bw()+
  theme(plot.title=element_text(hjust=0.5,size=20,margin=margin(b=10)),
        text=element_text(size=12),
        axis.title.y = element_text(margin=margin(r=20)),
        aspect.ratio=1,
        legend.title.align = 0.5)+
    scale_color_viridis(discrete=T)+
  labs(title="",
       y="k=4",
      color=expression(n[k]),
      x="")+
    guides(colour = guide_legend(override.aes = list(size=2)))

cc3<-ggplot(data=caveman %>% 
                     filter(CliqueSize==5) %>%
                     mutate(CliqueNum = as.factor(CliqueNum)) %>%
                     filter(ProbDiff == 1)
                   ,aes(y=Step, x=ChangeLink,color=CliqueNum))+
  stat_summary(fun="mean", geom="point", show.legend=T)+
  stat_summary(fun="mean", geom="line", show.legend=F,size=1.3)+
  theme_bw()+
  theme(plot.title=element_text(hjust=0.5,size=20,margin=margin(b=10)),
        text=element_text(size=12),
        axis.title.y = element_text(margin=margin(r=20)),
        aspect.ratio=1,
        legend.title.align = 0.5)+
    scale_color_viridis(discrete=T)+
  labs(title="",
       y="k=5",
      color=expression(n[k]),
      x="")+
    guides(colour = guide_legend(override.aes = list(size=2)))

cc4<-ggplot(data=caveman %>% 
                     filter(CliqueSize==6) %>%
                     mutate(CliqueNum = as.factor(CliqueNum)) %>%
                     filter(ProbDiff == 1)
                   ,aes(y=Step, x=ChangeLink,color=CliqueNum))+
  stat_summary(fun="mean", geom="point", show.legend=T)+
  stat_summary(fun="mean", geom="line", show.legend=F,size=1.3)+
  theme_bw()+
  theme(plot.title=element_text(hjust=0.5,size=20,margin=margin(b=10)),
        text=element_text(size=12),
        axis.title.y = element_text(margin=margin(r=20)),
        aspect.ratio=1,
        legend.title.align = 0.5)+
    scale_color_viridis(discrete=T)+
  labs(title="",
       y="k=6",
      color=expression(n[k]),
      x="")+
    guides(colour = guide_legend(override.aes = list(size=2)))

#Layout specified using patchwork library
cclayout<-"
AB
CD"

Fig5<-cc1+cc2+cc3+cc4+
  plot_layout(design=cclayout)+
  plot_annotation(title = 'Dynamic Caveman Networks', 
                  subtitle = 'Link Alteration Probability',
                  theme = theme(plot.title = element_text(hjust = 0.5,vjust=-2,size=25),
                                plot.subtitle = element_text(hjust=0.5,vjust=-125,size=20)))+
  plot_annotation(tag_levels = 'A')

Fig5
```

Plot for ring networks (SI Fig. 1)
```{r}
ring.melt <- reshape2::melt(ring %>%
                              mutate(Step=scale(Step)), id.vars = 'NumAgents', variable.name = 'Measure', 
    value.name = 'Performance') %>%
    filter(Measure == c('Step','Gini'))

SIFig1 <- ggplot(data=ring.melt %>% 
                   group_by(NumAgents,Measure) %>%
                   summarise_all(mean)) + 
  geom_line(aes(y=Performance,x=NumAgents, color = Measure), show.legend=F, size=1)+
  geom_point(aes(y=Performance,x=NumAgents, color = Measure), size=2.05)+
  theme_bw()+
  theme(plot.title=element_text(hjust=0.5),
        text=element_text(size=15),
                aspect.ratio=.8,                
        axis.title.y = element_text(margin=margin(r=20),size=20))+
  labs(title="Ring Networks",
       x="Number of Agents",
       y="Scaled Performance",
       color="Measure")+
  scale_color_manual(values = c("Gini" = '#00b0f0','Step' = '#ff0000'), labels=c('Gini','Steps'))


SIFig1
```

More In-depth Link change Plot (SI Fig. 2):
```{r}
change1<-ggplot(data=random %>% 
                     filter(NumAgents == 15) %>%
                     mutate(NumAgents = as.factor(NumAgents)) %>%
                     mutate(ProbEdge = as.factor(ProbEdge)) %>%
                     filter(ProbDiff == 1)
                   ,aes(y=Step, x=ChangeLink,color=ProbEdge))+
  stat_summary(fun="mean", geom="point", show.legend=F)+
  stat_summary(fun="mean", geom="line", show.legend=F,size=1.3)+
  theme_bw()+
  theme(plot.title=element_text(hjust=0.5,size=20,margin=margin(b=10)),
        text=element_text(size=12),
        axis.title.y = element_text(margin=margin(r=20)),
        aspect.ratio=1,
        legend.title.align = 0.5)+
    scale_color_viridis(discrete=T)+
  labs(title="N=15",
       y="",
      color="Population\nSize",
      x="")+
    guides(colour = guide_legend(override.aes = list(size=5)))

change2<-ggplot(data=random %>% 
                     filter(NumAgents == 25) %>%
                     mutate(NumAgents = as.factor(NumAgents)) %>%
                     mutate(ProbEdge = as.factor(ProbEdge)) %>%
                     filter(ProbDiff == 1)
                   ,aes(y=Step, x=ChangeLink,color=ProbEdge))+
  stat_summary(fun="mean", geom="point", show.legend=F)+
  stat_summary(fun="mean", geom="line", show.legend=F,size=1.3)+
  theme_bw()+
  theme(plot.title=element_text(hjust=0.5,size=20,margin=margin(b=10)),
        text=element_text(size=12),
        axis.title.y = element_text(margin=margin(r=20)),
        aspect.ratio=1,
        legend.title.align = 0.5)+
    scale_color_viridis(discrete=T)+
  labs(title="N=25",
       y="",
      color="Population\nSize",
      x="")+
    guides(colour = guide_legend(override.aes = list(size=5)))

change3<-ggplot(data=random %>% 
                     filter(NumAgents == 50) %>%
                     mutate(NumAgents = as.factor(NumAgents)) %>%
                     mutate(ProbEdge = as.factor(ProbEdge)) %>%
                     filter(ProbDiff == 1)
                   ,aes(y=Step, x=ChangeLink,color=ProbEdge))+
  stat_summary(fun="mean", geom="point", show.legend=F)+
  stat_summary(fun="mean", geom="line", show.legend=F,size=1.3)+
  theme_bw()+
  theme(plot.title=element_text(hjust=0.5,size=20,margin=margin(b=10)),
        text=element_text(size=12),
        axis.title.y = element_text(margin=margin(r=20)),
        aspect.ratio=1,
        legend.title.align = 0.5)+
    scale_color_viridis(discrete=T)+
  labs(title="N=50",
       y="",
      color="Population\nSize",
      x="")+
    guides(colour = guide_legend(override.aes = list(size=5)))

change4<-ggplot(data=random %>% 
                     filter(NumAgents == 100) %>%
                     mutate(NumAgents = as.factor(NumAgents)) %>%
                     mutate(ProbEdge = as.factor(ProbEdge)) %>%
                     filter(ProbDiff == 1)
                   ,aes(y=Step, x=ChangeLink,color=ProbEdge))+
  stat_summary(fun="mean", geom="point", show.legend=T)+
  stat_summary(fun="mean", geom="line", show.legend=F,size=1.3)+
  theme_bw()+
  theme(plot.title=element_text(hjust=0.5,size=20,margin=margin(b=10)),
        text=element_text(size=12),
        axis.title.y = element_text(margin=margin(r=20)),
        legend.title= element_text(size=15),
        aspect.ratio=1,
        legend.title.align = 0.5)+
    scale_color_viridis(discrete=T)+
  labs(title="N=100",
       y="",
      color="Edge Probability",
      x="")+
    guides(colour = guide_legend(override.aes = list(size=5)))

#Layout specified using patchwork library
layout3<-"ABCD"

SIFig2<-change1+change2+change3+change4+
  plot_layout(design=layout3)+
  plot_annotation(title = 'Probability of Link Alteration', 
                  theme = theme(plot.title = element_text(hjust = 0.5,size=25,vjust=-43)))

SIFig2
```

Calculate Success Rates (SI Table 1):
```{r}
successrand <- read.csv(paste(path,"random.csv", sep='')) %>% 
  group_by(NumAgents) %>%
  summarise(SuccessRate = mean(Crossover)) %>%
  mutate(Network = "Random")

successcave <- read.csv(paste(path,"caveman.csv", sep='')) %>% 
  group_by(NumAgents) %>%
  summarise(SuccessRate = mean(Crossover)) %>%
  mutate(Network = "Caveman")
  
successring <- read.csv(paste(path,"ring.csv", sep='')) %>% 
  group_by(NumAgents) %>%
  summarise(SuccessRate = mean(Crossover)) %>%
  mutate(Network = "Ring")

success<- list(successring,successrand,successcave) %>%
  reduce(full_join)
```

